apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: {{AWS_BUCKET}}
  AWS_PROFILE: {{AWS_PROFILE}}
  AWS_REGION: {{AWS_REGION}}
  POSTGRESS_DB: {{POSTGRESS_DB}}
  POSTGRESS_HOST: {{POSTGRESS_HOST}}
  URL: {{APP_URL}}
metadata:
  name: env-config
  